# Generated by Django 6.0.4 on 2026-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='budget_per_team',
            field=models.DecimalField(decimal_places=1, default=150.0, max_digits=8),
        ),
    ]
