# Generated by Django 6.0.4 on 2026-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchplayerstat_team_barons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
