# Generated by Django 6.0.4 on 2026-06-12 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leagues.league')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_scores', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score Fantasy',
                'verbose_name_plural': 'Scores Fantasy',
                'ordering': ['-points'],
                'unique_together': {('user', 'league', 'match')},
            },
        ),
    ]
