# Generated by Django 6.0.4 on 2026-06-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_game_name', models.CharField(max_length=50, unique=True)),
                ('team', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('support', 'Support')], max_length=10)),
                ('region', models.CharField(choices=[('LEC', 'LEC'), ('LCK', 'LCK'), ('LCS', 'LCS'), ('LPL', 'LPL')], max_length=5)),
                ('price', models.DecimalField(decimal_places=1, default=10.0, max_digits=8)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Joueur Pro',
                'verbose_name_plural': 'Joueurs Pro',
                'ordering': ['region', 'team', 'role'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30)),
                ('games_played', models.IntegerField(default=0)),
                ('kills', models.FloatField(default=0.0)),
                ('deaths', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('kda', models.FloatField(default=0.0)),
                ('cs_per_min', models.FloatField(default=0.0)),
                ('gold_per_min', models.FloatField(default=0.0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('damage_per_min', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Stats Joueur',
                'verbose_name_plural': 'Stats Joueurs',
                'unique_together': {('player', 'season')},
            },
        ),
    ]
