# Generated by Django 6.0.4 on 2026-05-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
