# Generated by Django 6.0.4 on 2026-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_demandeinscription_utilisateur_email_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('joueur', 'Joueur'), ('manager', 'Manager'), ('admin', 'Administrateur')], default='joueur', max_length=10),
        ),
    ]
