# Generated by Django 6.0.4 on 2026-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='region',
            field=models.CharField(choices=[('LEC', 'LEC'), ('LCK', 'LCK'), ('LCS', 'LCS'), ('LPL', 'LPL'), ('VCS', 'VCS'), ('LJL', 'LJL'), ('PCS', 'PCS'), ('CBLOL', 'CBLOL')], max_length=5),
        ),
    ]
