# Generated by Django 6.0.4 on 2026-06-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('LEC', 'LEC'), ('LCK', 'LCK'), ('LCS', 'LCS'), ('LPL', 'LPL')], max_length=5)),
                ('image_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Équipe Pro',
                'verbose_name_plural': 'Équipes Pro',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('LEC', 'LEC'), ('LCK', 'LCK'), ('LCS', 'LCS'), ('LPL', 'LPL')], max_length=5)),
                ('tournament', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('live', 'En direct'), ('finished', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=20)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.proteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.proteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='matches.proteam')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('vision_score', models.IntegerField(default=0)),
                ('duration_minutes', models.FloatField(default=30.0)),
                ('won', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='players.player')),
            ],
            options={
                'verbose_name': 'Stat Joueur (Match)',
                'verbose_name_plural': 'Stats Joueurs (Match)',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
