# Generated by Django 6.0.4 on 2026-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_region_alter_proteam_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayerstat',
            name='team_barons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='team_dragons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayerstat',
            name='team_towers',
            field=models.IntegerField(default=0),
        ),
    ]
